[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ICD11_rtd"
authors = [{name = "Justpsychiatry", email = "dr.waleed@outlook.com"}]
dynamic = ["version", "description"]
